# MKDOCS navigation structure and configuration
---
site_name: IS-IS Labs
docs_dir: docs
site_dir: _html
repo_url: https://github.com/bgplab/isis
site_url: https://isis.bgplabs.net/
site_description: Hands-on IS-IS labs using virtual devices
site_author: Ivan Pepelnjak, ipSpace.net AG
extra:
  toc_sidebar: False
  nav:
    'Overview': ''
    'Installation': '1-setup'
    'GitHub Codespaces': '4-codespaces'
    'Upcoming Labs': '3-upcoming'
    'About': '99-about'

copyright: (C) 2023–2025 Ivan Pepelnjak (ipSpace.net AG)
plugins:
- search
- include_dir_to_nav
nav:
- Home:
  - index.md
  - 99-about.md
- Installation:
  - 1-setup.md
  - 4-codespaces.md
- Basics:
  - Overview: basic/index.md
  - basic/0-frrouting.md
  - basic/1-simple-ipv4.md
  - basic/2-explore.md
  - basic/3-p2p.md
  - basic/4-metric.md
  - basic/5-ipv6.md
  - basic/6-level-2.md
  - basic/7-unnumbered.md

- Features:
  - feature/1-passive.md
  - feature/2-dis.md
  - feature/3-md5.md
  - feature/4-hide-transit.md
  - feature/5-drain.md
  - feature/6-timers.md
  - feature/7-redistribute.md

- "Upcoming":
  - Overview: 3-upcoming.md

markdown_extensions:
- footnotes
- abbr
- def_list
- admonition
- attr_list
- sane_lists
- smarty
- nl2br

theme:
  name: mkdocs
  custom_dir: _mkdocs_theme
  navigation_depth: 3
